### ISSUE TITLE
Add debit card donation method or change "credit card" to just "card"

### ISSUE THREAD

**Issue by lbraun** [lbraun/thanksgiving#2]

**Comment by narsbarz** [comment]
Still installing stuff to get this running on my computer! Stay tuned for actual work on this ticket

**Comment by lbraun** [comment]
oh cool! just seeing this now. let me know if you want to set up a time to hack 😄

**Comment by qubist** [comment]
@narichasavanorkejoyce Would you like me to take this over? Also happy to help you set up as much as I can or leave it for you later!
