### ISSUE TITLE
New donation bug

### ISSUE THREAD

**Issue by lbraun** [lbraun/thanksgiving#20]
Can't access the new donation page for some reason

**Comment by bradgreen3** [comment]
I am able to access the page locally with no problems using OSX Sierra and Chrome. Are you receiving any errors, or is there simply no link? Are you running it locally?

**Comment by lbraun** [comment]
Hey Brad, so glad to have you contributing! I think this is an old issue that has since been fixed. I'm going to close it and we can always reopen if necessary.
