### ISSUE TITLE
Change to human_attribute_name & prep for translations

### ISSUE THREAD

**Issue by qubist** [lbraun/thanksgiving#61]
From @lbraun:

> Yeah we should use human_attribute_name instead of humanize:
https://guides.rubyonrails.org/i18n.html#translations-for-active-record-models

> Translations are stored in https://github.com/lbraun/thanksgiving/tree/main/config/locales

> That's kind of a weird structure I started for them there, we could switch to having just one file for all english translations. But translations is definitely the way to handle this.

**Comment by qubist** [comment]
I think one file for all english translations is the way to go. @lbraun want to paircode on this issue sometime soon?

**Comment by lbraun** [comment]
Yeah, but I'm going to the Adirondacks until next Wednesday. Let's talk after that!

**Comment by qubist** [comment]
boom
